spring:
  cloud:
    aws:
      credentials:
        access-key: ${AWS_ACCESS_KEY}
        secret-key: ${AWS_SECRET_KEY}
      region:
        static: ap-northeast-2
      s3:
        bucket: gg2.0
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/gg2_db
    username: postgres
    password: '0000'
    hikari:
      maximum-pool-size: 20
      minimum-idle: 10
      connection-timeout: 30000
      idle-timeout: 600000
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  servlet:
    multipart:
      enabled: true
      max-file-size: 10MB       # 개별 파일의 최대 크기
      max-request-size: 10MB    # 전체 요청의 최대 크기
jwt:
  secret: K3fLxByYYb7nTMTz4j/JvyuBqvv7sC88XhqgG/7aT7s=
  access-token-validity-in-seconds: 1800
  refresh-token-validity-in-seconds: 604800
logging:
  level:
    org.springframework.security: INFO
    org.hibernate.orm.jdbc.bind: TRACE
    com.ggv2.goldenglobe_renewal.domain.chatbot: DEBUG
ai:
  server:
    url: http://localhost:8000