spring:
  cloud:
    aws:
      credentials:
        access-key: ${AWS_ACCESS_KEY}
        secret-key: ${AWS_SECRET_KEY}
      region:
        static: ap-northeast-2
      s3:
        bucket: gg2.0
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/gg2_db
    username: postgres
    password: '0000'
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
jwt:
  secret: K3fLxByYYb7nTMTz4j/JvyuBqvv7sC88XhqgG/7aT7s=
  access-token-validity-in-seconds: 1800
  refresh-token-validity-in-seconds: 604800